services:
  - type: web
    name: rentease-web
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://renteaseapptestapi.onrender.com/api